print *,'USAGE'
print *,'gnuout [OPTIONS] < input_file'
print *,''
print *,'Plots a 2D plot, using standart Gnuplot package (must be installed).'
print *,'All keywords (output file type, line style etc.) see in Gnuplot manuals'
print *,''
print *,'OPTIONS are:'
print *,''
print *,'-t, --title TITLE      - set plot title to TITLE'
print *,'-o, --output FILENAME  - set output file name (use together with --type)'
print *,'-s, --style LINESTYLE  - set line style (default linespoints)'
print *,'-l, --log [x|y|xy]     - turns axises to logarithmic scale'
print *,'--type                 - set type of the output file (for example: postscript)'
print *,'-a, --auto             - takes line number for X column'
print *,'-x N1,N2               - take X data from column N1, Y data from column N2 (default 1,2)'
print *,'--help                 - show this help and exit'
print *,''
print *,'Written by A.A.Mints (minzastro@yandex.ru) 2006-2007.'
print *,''
